name: Build, Scan, and Push Docker Image to ACR

on:
  push:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'Dockerfile'

permissions:
  id-token: write
  contents: read

env:
 
  DOCKER_IMAGE_NAME: ai-dc-monitor
  ACR_SERVER: ${{ secrets.ACR_SERVER }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      
      - name: ACR login (OIDC)
        uses: azure/docker-login@v2
        with:
          login-server: ${{ env.ACR_SERVER }}

      # Build a local image for security scan
      - name: Build image (for scan)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ env.ACR_SERVER }}/${{ env.DOCKER_IMAGE_NAME }}:scan
          load: true

      - name: Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.ACR_SERVER }}/${{ env.DOCKER_IMAGE_NAME }}:scan
          format: table
          exit-code: '0'                # don't fail the build on findings
          severity: 'CRITICAL,HIGH'

      
      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.ACR_SERVER }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.run_number }}
            ${{ env.ACR_SERVER }}/${{ env.DOCKER_IMAGE_NAME }}:latest

